#' Plot likelihood graphs
#' 
#' @description
#' Plots the likelihood files generated by the Java code
#' 
#' @param file_paths
#'   File paths to the likelihood txt files to plot in the same graph
#' @param group_names
#'   The name for each file path (needs to be the same length as \code{file_paths}).
#' @param subset
#'   Numeric vector containing the subset of iterations to use.
#'   
#' @return
#'   ggplot2 object.
#'
#' @export
plot_likelihoods <- function(file_paths, group_names = NULL, subset = NULL) {
  stopifnot(file.exists(file_paths),
            length(group_names) == 0 || length(group_names) == length(file_paths))

  # Calculate df
  for(file_no in seq_along(file_paths)){
    if(file_no == 1){ #file_no <- 1
      df <- read.table(file = file_paths[file_no])
      df$group <- group_names[file_no]
    } else {
      next_df <- read.table(file = file_paths[file_no])
      next_df$group <- group_names[file_no]
      df <- rbind(df, next_df)
    }
  }
  colnames(df)[1:2] <- c("Iteration", "Likelihood")
  if(!is.null(group_names)) colnames(df)[3] <- "Group"  
  if(!is.null(subset)) df <- df[df$Iteration %in% subset,]
  
  if(!is.null(group_names)){
    zp1 <- ggplot(data = df,
                  aes(x = Iteration, y = Likelihood, group = Group, colour = factor(Group)))
    zp1 <- zp1 + scale_colour_brewer(palette="Set1",
                                     guide_legend(title = "Chain"))
  } else {
    zp1 <- ggplot(data = df,
                  aes(x = Iteration, y = Likelihood))
  }
  zp1 <- zp1 + geom_line()
  zp1 <- zp1 + geom_point()
  zp1 <- zp1 + scale_x_continuous("Iteration")
  zp1 <- zp1 + scale_y_continuous("Log-Likelihood") 
  zp1 <- zp1 + theme_bw()
  zp1
}